import { motion, useScroll } from "framer-motion"
import Head from 'next/head'
import About from '../components/About'
import Contact from '../components/Contact'
import Footer from '../components/Footer'
import Hero from '../components/Hero'
import Portfolio from '../components/Portfolio'
import Skill from '../components/Skill'
import Testimonial from '../components/Testimonial'

export default function Home() {
  const { scrollYProgress } = useScroll();

  return (
    <div>
      <Head>
        <title>HimuDev- Folio</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <motion.div
        className="progress-bar"
        style={{ scaleX: scrollYProgress }}
      />
      <Hero />
      <About />
      <Skill />
      <Portfolio />
      <Testimonial />
      <Contact />
      <Footer />
    </div>
  )
}
